baseURL = "https://miidas.github.io/blog/"
languageCode = "ja"
title = "miidas blog"
theme = "hugo-theme-hello-friend-ng"
hasCJKLanguage = true

[params]
  description = "なんか書く。"
  enableSharingButtons = true
  defaultTheme = "dark"

[languages]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
